name = "taiwan-fin-hub"
main = "src/index.ts"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "../web/dist", binding = "ASSETS" }
browser = { binding = "BROWSER" }

[[d1_databases]]
binding = "DB"
database_name = "taiwan-fin-hub"
database_id = "c56987fa-0ab5-4237-bdd2-6dcaef9fd636"
remote = true
migrations_dir = "../../packages/db/migrations"
